[tool.poetry]
name = "poetry-science-env"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
include = ["pyproject.toml"]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.10"
numpy = "^1.23.4"
pandas = "^1.5.1"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
scikit-learn = "^1.2.2"
networkx = "^3.0"
numba = "^0.56.4"
awswrangler = "^2.20.1"
ipython = "^8.12.0"
ipykernel = "^6.22.0"
contexttimer = "^0.3.3"
seaborn = "^0.12.2"
tqdm = "^4.65.0"
jupyter = "^1.0.0"
s3contents = "^0.10.0"

[tool.poetry.group.chemistry]
optional = true

[tool.poetry.group.chemistry.dependencies]
rdkit-pypi = "^2022.9.5"
matchms = "^0.18.0"

[tool.poetry.group.torch]
optional = true

[tool.poetry.group.torch.dependencies]
torch = "^2.0.0"
pytorch-lightning = "^2.0.1"
transformers = "^4.27.4"
wandb = "^0.14.0"

[tool.poetry.group.metabolomics]
optional = true

[tool.poetry.group.metabolomics.dependencies]
metabolomics = {git = "https://github.com/enveda/metabolomics.git", rev = "v0.3.4"}

